# Generated by Django 4.2.7 on 2025-11-01 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('nitrogen_percent', models.FloatField(default=0, help_text='N percentage')),
                ('phosphorus_percent', models.FloatField(default=0, help_text='P2O5 percentage')),
                ('potassium_percent', models.FloatField(default=0, help_text='K2O percentage')),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, help_text='Price per unit', max_digits=10)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('ton', 'Ton'), ('bag', 'Bag (50kg)')], default='kg', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FertilizerRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('applied', 'Applied')], default='draft', max_length=20)),
                ('crop_nitrogen_requirement', models.FloatField(default=0)),
                ('crop_phosphorus_requirement', models.FloatField(default=0)),
                ('crop_potassium_requirement', models.FloatField(default=0)),
                ('soil_nitrogen_ppm', models.FloatField(default=0)),
                ('soil_phosphorus_ppm', models.FloatField(default=0)),
                ('soil_potassium_ppm', models.FloatField(default=0)),
                ('soil_ph', models.FloatField(default=7.0)),
                ('nitrogen_needed_kg', models.FloatField(default=0)),
                ('phosphorus_needed_kg', models.FloatField(default=0)),
                ('potassium_needed_kg', models.FloatField(default=0)),
                ('estimated_total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='parcels.landparcel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(help_text='Quantity needed')),
                ('unit', models.CharField(default='kg', max_length=10)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nitrogen_contribution_kg', models.FloatField(default=0)),
                ('phosphorus_contribution_kg', models.FloatField(default=0)),
                ('potassium_contribution_kg', models.FloatField(default=0)),
                ('fertilizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fertilizers.fertilizerproduct')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fertilizers.fertilizerrecommendation')),
            ],
            options={
                'ordering': ['recommendation', 'fertilizer'],
            },
        ),
    ]
