# Generated by Django 4.2.7 on 2025-11-01 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('nitrogen_requirement', models.FloatField(default=0, help_text='kg/ha')),
                ('phosphorus_requirement', models.FloatField(default=0, help_text='kg/ha')),
                ('potassium_requirement', models.FloatField(default=0, help_text='kg/ha')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LandParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('area_hectares', models.FloatField(help_text='Area in hectares')),
                ('soil_type', models.CharField(choices=[('sandy', 'Sandy'), ('loamy', 'Loamy'), ('clay', 'Clay'), ('silty', 'Silty'), ('peat', 'Peat')], default='loamy', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parcels.crop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_parcels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoilTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField()),
                ('nitrogen_ppm', models.FloatField(default=0, help_text='Nitrogen in ppm (parts per million)')),
                ('phosphorus_ppm', models.FloatField(default=0, help_text='Phosphorus in ppm')),
                ('potassium_ppm', models.FloatField(default=0, help_text='Potassium in ppm')),
                ('ph_level', models.FloatField(default=7.0, help_text='pH level (0-14)')),
                ('organic_matter_percent', models.FloatField(default=0, help_text='Organic matter percentage')),
                ('test_report', models.FileField(blank=True, null=True, upload_to='soil_tests/')),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('parcel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soil_test', to='parcels.landparcel')),
            ],
            options={
                'ordering': ['-test_date'],
            },
        ),
    ]
